pigrpg:
  debuger: false
  enable:
    RCList: true
    Friend: true
    Trade: true
    Sale: true
    Teleport: true
    Score: true
  rclist:
    cancel: true
  playerinfo:
    type: auto
    custom:
    - 名称:</id/>
    - 位置:</world/>(</x/>,</y/>,</z/>)
    - 等级:</level/>
    - OP:</op/>
    - 允许飞行:</fly/>
  teleport:
    warp:
      enable: true
    friend:
      enable: true
      overworld: true
      allworld: true
      enableworld:
      - world
    cooldown: 5000
  score:
    autofresh: true
    freshtime: 1000
    head: §6§l[PigRPG]
    scores:
    - '&4&lHP:</currenthealth/>/</maxhealth/>'
    - '&3Level:</level/>'
    - '&3EXP:</exp/>'