pigrpg:
  enable:
    RCList: true
    Friend: true
  rclist: 
    cancel: true
  playerinfo:
    type: auto
    custom:
    - 名称:</id/>
    - 位置:</world/>(</x/>,</y/>,</z/>)
    - 等级:</level/>
    - OP:</op/>
    - 允许飞行:</fly/>