name: PigRPG
main: com.github.xzzpig.pigrpg.Main
version: V2.0
author: xzzpig
depend: [Essentials, BarAPI,PigAPI] 
commands:
  pigrpg:
    description: 幻猪的RPG插件的命令帮助
    usage: §6[PigRPG]§2查看幻猪的RPG插件帮助:/pr help
    aliases: [pr]
